apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermariogame-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermariogame
  template:
    metadata:
      labels:
        app: supermariogame
    spec:
      nodeSelector:
        kubernetes.io/arch: amd64  # Force compatible architecture
      containers:
<<<<<<< HEAD
      - name: supermariogame-container
        image: puthurjohnny/supermarioproj:2
=======
      - image: puthurjohnny/supermarioproj:1
        name: supermariogame-container
>>>>>>> 6eff0a45ef2d3d95cd0175a7a4df37a7f90c4231
        ports:
        - containerPort: 8080
        imagePullPolicy: Always  # Ensure fresh pull
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: supermariogame-service
spec:
  selector:
    app: supermariogame
  ports:
  - protocol: TCP
    port: 8600        # External port
    targetPort: 8080  # Container port
  type: LoadBalancer
